
version: "3"

services:
  app:
    image: snaksa/spotify-downlader-frontend
    build:
      context: .
    container_name: spotify-frontend
    # volumes:
    #  - ./server.js:/usr/src/app/server.js
    ports:
      - "3001:3000"
